[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Mirek Simek", email = "miroslav.simek@gmail.com"},
]
dependencies = []
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]