#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

python -m pip install pip-tools
pip-compile -U -o .requirements.txt requirements.in
pip install -r .requirements.txt

exit 0
