#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -e

if [[ "$EXTRAS" == "invenio3.5test" ]]; then
  poetry add --optional "invenio[base,metadata,files,postgresql,elasticsearch7,tests]>=3.5.0,<3.6.0"
fi
poetry install --extras ${EXTRAS}
pip freeze
