# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Upload an original package to CESNET GitLab

on:
  workflow_call:
    secrets:
      TWINE_USERNAME:
        required: true
      TWINE_PASSWORD:
        required: true
    inputs:
      oarepo:
        description: OARepo version (13, ...)
        required: true
        default: "14"
        type: string
      python:
        description: Python version
        required: true
        default: "3.13"
        type: string

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Download artifacts from extract_requirements
        uses: actions/download-artifact@v4
        with:
          name: rdm_versions
          path: artifacts/requirements

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      # already in install_python
      # - name: Install build tools
      #   uses: ./.github/actions/install_build_tools

      - name: Download versions of packages from pypi and cesnet pypi
        run: |
          echo "[" > pypi_versions.json
          echo "[" > cesnet_pypi_versions.json

          cat artifacts/requirements/rdm_requirements.txt | \
            egrep '^invenio-' | \
            sed 's/==.*//' | \
            sed 's/@.*//' | while read PACKAGE ; do

            echo "Package to check: ${PACKAGE}"

            echo "," >> pypi_versions.json
            pip index versions ${PACKAGE} --json >> pypi_versions.json

            echo "," >> cesnet_pypi_versions.json
            pip index versions --index-url ${CESNET_PYPI_URL}/simple ${PACKAGE} --json >> cesnet_pypi_versions.json
          done

          echo "]" >> pypi_versions.json
          echo "]" >> cesnet_pypi_versions.json
          # cleanup leading commas
          cat pypi_versions.json | tr -d '\n' | sed 's/\[,/\[/' > tmp.json
          mv tmp.json pypi_versions.json
          cat cesnet_pypi_versions.json | tr -d '\n' | sed 's/\[,/\[/' > tmp.json
          mv tmp.json cesnet_pypi_versions.json

      - name: Get differences in versions
        run: |
          bt_compare_pypi_versions \
              pypi_versions.json \
              cesnet_pypi_versions.json \
              not_uploaded_packages.txt \
              non_existing.txt

          echo "The following packages with versions do not exist in CESNET pypi:"
          echo "================================================================="
          cat non_existing.txt || echo "All packages exist"

      - name: Upload to CESNET pypi
        run: | # shell
          uv venv .venv
          source .venv/bin/activate
          uv pip install -U "setuptools<82.0.0"
          pip install twine
          export TWINE_USERNAME=${{ secrets.TWINE_USERNAME }}
          export TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }}
          if [ -z "${TWINE_USERNAME}" ] ; then
            echo "TWINE_USERNAME is not set, will not upload to pypi"
            exit 1
          fi
          if [ -z "${TWINE_PASSWORD}" ] ; then
            echo "TWINE_PASSWORD is not set, will not upload to pypi"
            exit 1
          fi

          cat non_existing.txt | while read PACKAGE_WITH_VERSION; do
            echo "Uploading ${PACKAGE_WITH_VERSION} to CESNET pypi"
            (
              if [ -d tmp ] ; then
                rm -rf tmp
              fi  
              mkdir tmp
              cd tmp           
              pip download --no-deps --only-binary :all: ${PACKAGE_WITH_VERSION} || true
              pip download --no-deps --no-binary :all: ${PACKAGE_WITH_VERSION} || true
            
              # if there is at least one file, upload it
              if find . -type f -print -quit | grep -q . ; then
                echo "Uploading $(ls .) to CESNET pypi"
                twine upload --verbose --non-interactive --repository-url ${CESNET_PYPI_URL} *.tar.gz *.whl  || echo "Failed to upload to pypi"
              else
                echo "No files downloaded for ${PACKAGE_WITH_VERSION}, skipping upload"
              fi
            )
          done
