# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Install and test current Invenio RDM

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (13, ...)
        required: true
        default: "14"
        type: string
      python:
        description: Python version
        required: true
        default: "3.13"
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}
  QASE_TESTOPS_PROJECT: ${{ secrets.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TESTOPS_API_TOKEN }}
  QASE_ENVIRONMENT: ${{ secrets.QASE_ENVIRONMENT }}
  QASE_MODE: ${{ secrets.QASE_MODE }}
  INVENIO_DATACITE_USERNAME: ${{ secrets.INVENIO_DATACITE_USERNAME }}
  INVENIO_DATACITE_PASSWORD: ${{ secrets.INVENIO_DATACITE_PASSWORD }}
  INVENIO_DATACITE_PREFIX: ${{ secrets.INVENIO_DATACITE_PREFIX }}
  HEADLESS: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env # TODO: change the branch when merging to main
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install os prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Install python
        uses: ./.github/actions/install_python # TODO: change the branch when merging to main
        with:
          python-version: ${{ inputs.python }}

      - uses: actions/setup-node@v6

      - name: Create a RDM instance
        run: |
          mkdir .tests
          cd .tests
          invenio-cli init -c v${OAREPO_VERSION}.0 --config ../rdm/invenio-cli.cfg </dev/null

          # replace the python version in Pipfile with the one we want to test
          cp my-site/Pipfile my-site/Pipfile.bak
          cat my-site/Pipfile.bak | sed "s/python_version.*/python_version=\"${PYTHON_VERSION}\"/" > my-site/Pipfile

          # TODO: replace app rdm with those being used in workflow (just for sure)

      - name: Install RDM
        run: |
          cd .tests/my-site
          invenio-cli check-requirements --development
          invenio-cli install

      - name: Start RDM services
        run: |
          cd .tests/my-site
          invenio-cli services setup

      - name: Run RDM UI tests
        run: |

          export INVENIO_BASE_URL=https://127.0.0.1:5000/

          export INVENIO_USER_EMAIL=test@test.com
          export INVENIO_USER_PASSWORD=password
          export INVENIO_ACCOUNTS_DEFAULT_USER_VISIBILITY=public
          export INVENIO_ACCOUNTS_DEFAULT_EMAIL_VISIBILITY=public

          set -x
          cd .tests/my-site
          pipenv run invenio users create -a -c $INVENIO_USER_EMAIL --password $INVENIO_USER_PASSWORD --profile '{"full_name": "Test User"}'
          pipenv run invenio users create -a -c petr.brablc@gmail.com --password 123456 --profile '{"full_name": "Brablc gmail"}'
          pipenv run invenio users create -a -c petr.brablc@cesnet.cz --password 123456 --profile '{"full_name": "Brablc cesnet"}'


          echo "INVENIO_DATACITE_USERNAME: ${INVENIO_DATACITE_USERNAME}"
          echo "INVENIO_DATACITE_PASSWORD: ${INVENIO_DATACITE_PASSWORD}"
          echo "INVENIO_DATACITE_PREFIX: ${INVENIO_DATACITE_PREFIX}"

          export INVENIO_DATACITE_USERNAME
          export INVENIO_DATACITE_PASSWORD
          export INVENIO_DATACITE_PREFIX

          echo "DATACITE_ENABLED = True" >>invenio.cfg

          echo "print('Invenio CFG loaded')" >>invenio.cfg
          echo "import os" >>invenio.cfg

          echo "print('datacite username ', os.environ.get('INVENIO_DATACITE_USERNAME', '').lower())" >>invenio.cfg
          echo "print('datacite password ', os.environ.get('INVENIO_DATACITE_PASSWORD', '').lower())" >>invenio.cfg
          echo "print('datacite prefix   ', os.environ.get('INVENIO_DATACITE_PREFIX', '').lower())" >>invenio.cfg

          invenio-cli run >invenio.log 2>&1 &

          INVENIO_PID=$!
          sleep 120

          cd ../..

          git clone https://github.com/oarepo/invenio-rdm-qa.git
          cd invenio-rdm-qa

          npm ci
          npx playwright install --with-deps

          npx playwright test

          kill $INVENIO_PID || true
          sleep 5
          kill -9 $INVENIO_PID || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: invenio.log
          path: invenio.log
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
