# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Install and test current Invenio RDM

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}
  QASE_TESTOPS_PROJECT: ${{ secrets.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TESTOPS_API_TOKEN }}
  QASE_ENVIRONMENT: ${{ secrets.QASE_ENVIRONMENT }}
  QASE_MODE: ${{ secrets.QASE_MODE }}
  HEADLESS: true

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env      # TODO: change the branch when merging to main
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install os prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick


      - name: Install python
        uses: ./.github/actions/install_python      # TODO: change the branch when merging to main
        with:
          python-version: ${{ inputs.python }}

      - uses: actions/setup-node@v4

      - name: Create a RDM instance
        run: |
          mkdir .tests
          cd .tests
          invenio-cli init -c v${OAREPO_VERSION}.0 --config ../rdm/invenio-cli.cfg </dev/null
          
          # replace the python version in Pipfile with the one we want to test
          cp my-site/Pipfile my-site/Pipfile.bak
          cat my-site/Pipfile.bak | sed "s/python_version.*/python_version=\"${PYTHON_VERSION}\"/" > my-site/Pipfile

          # TODO: replace app rdm with those being used in workflow (just for sure)

      - name: Install RDM
        run: |
          cd .tests/my-site
          invenio-cli check-requirements --development
          invenio-cli install

      - name: Start RDM services
        run: |
          cd .tests/my-site
          invenio-cli services setup
          
      - name: Run RDM UI tests
        run: |

          export INVENIO_BASE_URL=https://127.0.0.1:5000/

          export INVENIO_USER_EMAIL=test@test.com
          export INVENIO_USER_PASSWORD=password

          set -x
          cd .tests/my-site
          pipenv run invenio users create -a -c $INVENIO_USER_EMAIL --password $INVENIO_USER_PASSWORD --profile '{"full_name": "Test User"}'
          invenio-cli run >invenio.log 2>&1 &
          INVENIO_PID=$!
          sleep 120

          cd ../..

          git clone https://github.com/oarepo/invenio-rdm-qa.git
          cd invenio-rdm-qa
          
          npm ci
          npx playwright install --with-deps

          npx playwright test

          kill $INVENIO_PID
          sleep 5
          kill -9 $INVENIO_PID

      - uses: actions/upload-artifact@v4
        with:
          name: invenio.log
          path: invenio.log
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
