# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create a fork of invenio rdm library

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string
      package_and_version:
        description: "Package and version to fork"
        # input example: {"package": "invenio-communities", "version": "13.0.6", "features": ["kwargs-extension"]}
        required: true
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}
  PACKAGE_AND_VERSION: ${{ inputs.package_and_version }}
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - name: Convert package and version to environment variables
        run: |
          cat <<EOF >> $GITHUB_ENV
          
          PACKAGE=$(echo "${PACKAGE_AND_VERSION}" | jq -r '.package')
          VERSION=$(echo "${PACKAGE_AND_VERSION}" | jq -r '.version')
          FEATURES=$(echo "${PACKAGE_AND_VERSION}" | jq -c '.features')

          INVENIO_VERSION=v$(echo "${PACKAGE_AND_VERSION}" | jq -r '.version')
          OAREPO_VERSION=oarepo-$(echo "${PACKAGE_AND_VERSION}" | jq -r '.version')

          EOF
          
          cat $GITHUB_ENV

      - name: Check if the package is already forked
        id: check_fork
        run: |
          mkdir -p .forks
          cd .forks
          gh repo clone oarepo/${PACKAGE}
          cd ${PACKAGE}
          git switch ${OAREPO_VERSION} && {
            echo "The fork already exists"
            echo "fork_already_exists=true" >> $GITHUB_ENV
            exit 0
          } || {
            echo "The fork does not exist, will try to create it"
            echo "fork_already_exists=false" >> $GITHUB_ENV
          }

      - name: Create a temporary fork of the package
        run: |
          cd .forks/${PACKAGE}
          git remote add upstream https://github.com/inveniosoftware/${PACKAGE}.git || true
          
          # remove a temporary fork
          git branch -D ${OAREPO_VERSION}-temporary || true
          
          # fetch invenio version and checkout it
          git fetch --tags upstream
          git fetch --all
          git checkout ${INVENIO_VERSION}
          
          # it is a tag, so create oarepo version from it
          git switch -c ${OAREPO_VERSION}-temporary

      - name: Apply feature branches
        run: |
          cd .forks/${PACKAGE}
          
          apply_feature() {
            feature=$1
            feature_base=$2
            feature_branch="oarepo-feature-${feature}"
            
            echo "Applying feature branch $feature_branch based on $feature_base onto ${OAREPO_VERSION}-temporary"
            git rev-list ${feature_branch} ^${feature_base}
            
            git switch ${OAREPO_VERSION}-temporary
            git cherry-pick --allow-empty --allow-empty-message ${feature_branch} ^${feature_base} 
          }
          
          echo "$FEATURES" | jq -c ".[]" | while read feature_rec ; do
            feature_name=$(echo $feature_rec | jq -r '.name')
            feature_base=$(echo $feature_rec | jq -r '.base')
            apply_feature $feature_name $feature_base
          done

      - name: Run tests on the patched package
        run: |
          cd .forks/${PACKAGE}
          if [ $(git rev-parse --abbrev-ref HEAD) != ${OAREPO_VERSION}-temporary ] ; then
            echo "The current branch is not ${OAREPO_VERSION}-temporary - probably bug in previous steps"
            exit 1
          fi

          uv venv --python=${PYTHON_VERSION}
          source .venv/bin/activate
          uv pip install -e '.[tests,opensearch2,s3,devs]'
          if [ -x ./run-tests.sh ] ; then
            ./run-tests.sh
          elif [ -x ./run_tests.sh ] ; then
            ./run_tests.sh
          else
            pytest tests
          fi

      - name: Rename a temporary fork to the final fork
        if: env.fork_already_exists != 'true'
        run: |
          cd .forks/${PACKAGE}
          git switch ${OAREPO_VERSION}-temporary
          git branch -m ${OAREPO_VERSION}
          echo "push_required=True" >> $GITHUB_ENV

      - name: Check if the temporary fork is the same as if original, if not, remove the original and rename temp to original
        if: env.fork_already_exists == 'true'
        run: |
          cd .forks/${PACKAGE}
          git diff --exit-code ${OAREPO_VERSION} ${OAREPO_VERSION}-temporary || {
            git branch -D ${OAREPO_VERSION}
            git switch ${OAREPO_VERSION}-temporary
            git branch -m ${OAREPO_VERSION}
            echo "push_required=True" >> $GITHUB_ENV
          }
#
#      - name: Push the fork to the remote
#        if: env.push_required == 'true'
#        run: |
#          cd .forks/${PACKAGE}
#          git push origin ${OAREPO_VERSION} --force
