# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create a fork of invenio rdm library

on:
  workflow_call:
    secrets:
      TWINE_USERNAME:
        required: true
      TWINE_PASSWORD:
        required: true
    inputs:
      oarepo:
        description: OARepo version (13, ...)
        required: true
        default: "14"
        type: string
      python:
        description: Python version
        required: true
        default: "3.13"
        type: string
      package:
        description: "Package to fork"
        required: true
        type: string
      force_new_versions:
        description: "Force new versions of forks and oarepo package"
        required: false
        default: "false"
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  OAREPO_MAJOR_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}
  PACKAGE: ${{ inputs.package }}
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Download artifacts from extract_requirements
        uses: actions/download-artifact@v4
        with:
          name: rdm_versions
          path: artifacts/requirements

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Create github app token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.OAREPO_BUMP_VERSION_CLIENT_ID }}
          private-key: ${{ secrets.OAREPO_BUMP_VERSION_CLIENT_PASSWORD }}

      - name: Convert package and version to environment variables. Create package-settings.json
        id: convert_package_and_version
        run: |
          cat artifacts/requirements/invenio-forks.json | jq -c ".pkg_index.\"${PACKAGE}\"" > package_settings.json

          cat <<EOF >> $GITHUB_ENV
          VERSION=$(cat package_settings.json | jq -r '.version')
          FEATURES=$(cat package_settings.json | jq -c '.features')

          PACKAGE_REPOSITORY=$(cat package_settings.json | jq -r '.repository')
          PACKAGE_REPOSITORY_URL=$(cat package_settings.json | jq -r '.repository_url')
          OAREPO_REPOSITORY=$(cat package_settings.json | jq -r '.oarepo_repository')
          PACKAGE_COMMIT=$(cat package_settings.json | jq -r '.commit')
          PACKAGE_CESNET_VERSION=$(cat package_settings.json | jq -r '.cesnet_version')
          PACKAGE_ALREADY_BUILT=$(cat package_settings.json | jq -r '.already_built')

          EOF

          echo "==== Package settings: ===="
          cat package_settings.json

          echo "==== Environment: ===="
          cat $GITHUB_ENV

      - name: Install python and tools
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - name: Install build tools
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        uses: ./.github/actions/install_build_tools

      - name: Git globals
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          git config --global user.email "integration-tests@oarepo.org"
          git config --global user.name "OARepo Bot"

      - name: Clone the package
        uses: actions/checkout@v4
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        with:
          repository: ${{env.OAREPO_REPOSITORY}}
          token: ${{ steps.app-token.outputs.token }}
          path: ".forks/${{env.PACKAGE}}"

      - name: Checkout the commit of the package
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          echo "::group::Will run: Setting up the correct branch"
          echo "gh repo clone ${OAREPO_REPOSITORY}"
          echo "cd $PACKAGE"
          echo "git fetch --tags upstream"
          echo "git fetch --all"
          echo "git checkout ${PACKAGE_COMMIT}"
          echo "git branch -D cherry-pick-temporary || true"
          echo "git switch -c cherry-pick-temporary"
          echo "::endgroup::"

          echo "::group::Running: Setting up the correct branch"
          cd .forks/${PACKAGE}
          git remote add upstream https://github.com/inveniosoftware/${PACKAGE}.git || true

          # fetch invenio version and check it out
          git fetch --tags upstream
          git fetch --all
          git checkout ${PACKAGE_COMMIT}
          git branch -D cherry-pick-temporary || true
          git switch -c cherry-pick-temporary
          echo "::endgroup::"

      - name: Apply feature branches
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}

          apply_feature() {
            feature=$1
            feature_base=$2
            feature_branch="oarepo-feature-${feature}"

            echo "::group::Will run: apply feature $feature, base: $feature_base, branch: $feature_branch"

            echo "git checkout $feature_branch"
            echo "git checkout $feature_base"
            echo "git checkout cherry-pick-temporary"
            echo "git rev-list ${feature_branch} ^${feature_base}"
            echo "git cherry-pick --allow-empty --allow-empty-message ${feature_branch} ^${feature_base}"
            echo "::endgroup::"

            echo "::group::Running: apply feature $feature, base: $feature_base, branch: $feature_branch"
            git checkout $feature_branch
            git checkout $feature_base
            git checkout cherry-pick-temporary

            echo git rev-list ${feature_branch} ^${feature_base}
            git rev-list ${feature_branch} ^${feature_base}
            

            echo git cherry-pick --allow-empty --allow-empty-message ${feature_branch} ^${feature_base} 
            git cherry-pick --allow-empty --allow-empty-message ${feature_branch} ^${feature_base} || {
              echo "Cherry-pick failed"
              git diff
              exit 1
            }
            echo "::endgroup::"
          }

          echo "$FEATURES" | jq -c ".[]" | while read feature_rec ; do
            feature_name=$(echo $feature_rec | jq -r '.name')
            feature_base=$(echo $feature_rec | jq -r '.base')
            feature_base_commit=$(echo $feature_rec | jq -r '.base_commit // ""')
            if [ -n "$feature_base_commit" ] ; then
              feature_base=$feature_base_commit
            fi
            apply_feature $feature_name $feature_base
          done

          if [ -f "oarepo-after-patch.sh" ]; then
            echo "::group::Will run: Post-patch script"
            echo "Running oarepo-after-patch.sh"
            echo "::endgroup::"
            echo "::group::Running: Post-patch script"
            bash oarepo-after-patch.sh || {
              echo "oarepo-after-patch.sh failed"
              exit 1
            }
            echo "::endgroup::"
          fi

          # show the diff
          git diff ${COMMIT}..HEAD

      - name: Create a summary of the changes
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: |
          cd .forks/${PACKAGE}

          # add the features to a file that will be committed to the package so that later we know
          # that the package was patched with these features
          main_package=$(echo $PACKAGE | sed 's/-/_/g' | sed 's/citeproc_py_styles/citeproc_styles/')

          cat <<EOF > ${main_package}/oarepo_changes.py
          # -*- coding: utf-8 -*-
          #
          # Copyright (C) 2024 CESNET.
          #
          # OARepo ecosystem is free software; you can redistribute it and/or modify it
          # under the terms of the MIT License; see LICENSE file for more details.
          #
          # This file was automatically generated by the integration tests to show which changes
          # were applied to the package.
          """Changes performed by oarepo-integration-tools."""

          # the code below is json, so need to define a couple of aliases just to be sure
          true = True
          """JSON True."""

          false = False
          """JSON False."""

          configuration = $(cat ../../package_settings.json)
                            
          EOF

          black ${main_package}/oarepo_changes.py

          echo "Created the following changes file:"
          cat ${main_package}/oarepo_changes.py
          git add ${main_package}/oarepo_changes.py
          git commit -m "Add changes file"

      - name: Bump version to a post version
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}

          # bump the version to a post version
          # this is nasty fix for the citeproc-py-styles, because library have separate version.py file with __version__
          if [ "$PACKAGE" = "citeproc-py-styles" ]; then
            version_file="citeproc_styles/version.py"
            sed 's/^__version__ = .*/__version__ = "'${PACKAGE_CESNET_VERSION}'"/' ${version_file} > ${version_file}.new
            mv ${version_file}.new ${version_file}
            echo "Version file ${version_file}:"
            cat ${version_file}
          else
            init_py=${PACKAGE//-/_}/__init__.py
            cat ${init_py} | sed 's/^__version__ = .*/__version__ = "'${PACKAGE_CESNET_VERSION}'"/' > ${init_py}.new
            mv ${init_py}.new ${init_py}
            echo "Version file ${init_py}:"
            cat ${init_py}
          fi

      - name: Apply entrypoint changes and add cesnet dependencies
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}
          if [ -f setup.cfg ] ; then
            echo "Applying entrypoint changes to setup.cfg"
            cp setup.cfg .setup.cfg.before-changes
            bt_apply_entrypoints ../../package_settings.json setup.cfg
            echo "Setup.cfg after changes:"
            cat setup.cfg
          else
            cp pyproject.toml .pyproject.toml.before-changes
            entrypoints=$(cat ../../package_settings.json | jq -r '.entrypoints // ""')
            if [ -n "$entrypoints" ] ; then
              echo "ERROR: There are entrypoint changes needed but no setup.cfg file found, cannot apply the changes"
              exit 1
            fi

          fi

      - name: Create a venv for translations and build process
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}
          uv venv --python=${PYTHON_VERSION} --seed
          source .venv/bin/activate
          uv pip install -U pip setuptools wheel babel

      - name: Compile translations if needed
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}
          source .venv/bin/activate
          python setup.py compile_catalog || true

      - name: Build the package in a venv to check that it works
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}
          source .venv/bin/activate
          uv build

      - name: Run tests on the patched package
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}
          if [ $(git rev-parse --abbrev-ref HEAD) != cherry-pick-temporary ] ; then
            echo "The current branch is not cherry-pick-temporary - probably bug in previous steps"
            exit 1
          fi

          # note: we need to use the version without entrypoints removed, that is why
          # .before-changes files are used. At the same time, we need to remove black and isort
          # asd the patches above might have created formatting inconsistencies.
          if [ -f setup.cfg ] ; then
            echo "::group::Will run: Removing black and isort from setup.cfg"
            echo "cp setup.cfg .setup.cfg.before-changes"
            echo "cat .setup.cfg.before-changes | sed 's/--black//' | sed 's/--isort//' | sed 's/--pydocstyle//' > setup.cfg"
            echo "::endgroup::"
            echo "::group::Running: Removing black and isort from setup.cfg"
            # do not check for black and isort - would make the patches too complicated          
            cp setup.cfg .setup.cfg.orig

            # add back lines removed by forks as they contain dependencies needed for the tests
            cat .setup.cfg.before-changes | sed "s/--black//" | sed 's/--isort//' | sed 's/--pydocstyle//' > setup.cfg
            cat setup.cfg
            echo "::endgroup::"

            bt_apply_test_entrypoints ../../package_settings.json setup.cfg

          elif [ -f pyproject.toml ] ; then
            echo "Removing black and isort from pyproject.toml"
            cp pyproject.toml .pyproject.toml.orig
            cat .pyproject.toml.before-changes | sed "s/--black//" | sed 's/--isort//' | sed 's/--pydocstyle//' > pyproject.toml
            cat pyproject.toml
          else
            echo "No setup.cfg or pyproject.toml found, cannot remove black and isort"
            exit 1
          fi

          bt_get_versions_to_fix_in_venv ../../artifacts/requirements/rdm_requirements.json ../../artifacts/requirements/invenio-forks.json versions_to_fix.txt

          echo "::group::Will run: Installation"
          echo "uv venv --python=${PYTHON_VERSION}"
          echo "source .venv/bin/activate"
          echo "uv pip install -e '.[tests,opensearch2,s3,devs, s3fs, oaipmh, rdf, sparql]'"
          cat versions_to_fix.txt | while read line ; do
            echo "uv pip install '$line'" --no-deps
          done

          for dep in $(cat ../../package_settings.json | jq -r '.cesnet_dependencies // [] | .[]') ; do
            echo "uv pip install --index=${CESNET_PYPI_URL}/simple --no-deps $dep"
          done
          echo "::endgroup::"

          echo "::group::Running: Installation"
          rm -rf .venv || true
          uv venv --python=${PYTHON_VERSION}
          source .venv/bin/activate
          uv pip install -e '.[tests,opensearch2,s3,devs, s3fs, oaipmh, rdf, sparql]'

          echo "Freeze before fixing versions:"
          echo "=============================="
          uv pip freeze
          echo "=============================="

          cat versions_to_fix.txt | while read line ; do
            echo "uv pip install '$line'" --no-deps
          done

          # for each of the cesnet_dependencies, remove the dependency by name and add the cesnet version
          for dep in $(cat ../../package_settings.json | jq -r '.cesnet_dependencies // [] | .[]') ; do
            echo "Installing cesnet dependency 'uv pip install --index=${CESNET_PYPI_URL}/simple --no-deps $dep'"
            dep_name=$(echo $dep | cut -d'=' -f1)
            uv pip uninstall $dep_name || true
            
            # try to install the cesnet version. If it is not yet ready, wait a bit and try again
            uv pip install --index=${CESNET_PYPI_URL}/simple --no-deps $dep || (
              sleep 180 # sleep 3 minutes before trying to retry
              while true ; do
                uv pip install --index=${CESNET_PYPI_URL}/simple --no-deps $dep && break || sleep 30
              done
            )
          done

          echo "Freeze after fixing versions:"
          echo "=============================="
          uv pip freeze
          echo "=============================="

          echo "::endgroup::"

          rm versions_to_fix.txt

          echo "::group::Installing containers"
          # if docker-services-cli is not installed, install it (invenio-collections do not have it)
          docker-services-cli --version || uv pip install docker-services-cli
          docker-services-cli up --db postgresql --search opensearch --mq rabbitmq --cache redis --env
          echo "::endgroup::"

          # package_settings.json contains optional tests.testopts array with testopts to be used when running tests
          TESTOPTS=$(cat ../../package_settings.json | jq -r '.tests[]?.testopts' | tr '\n' ' ')

          echo "::group::Will run: Tests"
          echo "export PYTHONWARNINGS=ignore"

          if [ -x ./run-tests.sh ] ; then
            echo "./run-tests.sh $TESTOPTS" 
          elif [ -x ./run_tests.sh ] ; then
            echo "./run_tests.sh $TESTOPTS"
          else
            echo "pytest tests $TESTOPTS"
          fi
          echo "::endgroup::"

          echo "::group::Running: Tests"
          export PYTHONWARNINGS=ignore

          if [ -x ./run-tests.sh ] ; then
            ./run-tests.sh $TESTOPTS
          elif [ -x ./run_tests.sh ] ; then
            ./run_tests.sh $TESTOPTS
          else
            pytest tests $TESTOPTS
          fi
          echo "::endgroup::"

          if [ -f .setup.cfg.orig ] ; then
            mv .setup.cfg.orig setup.cfg
          fi

          if [ -f .pyproject.toml.orig ] ; then
            mv .pyproject.toml.orig pyproject.toml
          fi

      - name: Upload to CESNET pypi
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        run: | # shell
          cd .forks/${PACKAGE}
          source .venv/bin/activate
          pip install twine

          export TWINE_USERNAME=${{ secrets.TWINE_USERNAME }}
          export TWINE_PASSWORD=${{ secrets.TWINE_PASSWORD }}

          if [ -z "${TWINE_USERNAME}" ] ; then
            echo "TWINE_USERNAME is not set, will not upload to pypi"
            exit 1
          fi
          if [ -z "${TWINE_PASSWORD}" ] ; then
            echo "TWINE_PASSWORD is not set, will not upload to pypi"
            exit 1
          fi
          twine upload --verbose --non-interactive --repository-url ${CESNET_PYPI_URL} dist/* || echo "Failed to upload to pypi"

      - name: Upload dist folder as artifact
        if: env.PACKAGE_ALREADY_BUILT != 'true'
        uses: actions/upload-artifact@v6
        with:
          name: dist-${{ env.PACKAGE }}
          path: dist
