# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create a fork of invenio rdm library

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string
      package_and_version:
        description: "Package and version to fork"
        # input example: {"package": "invenio-communities", "version": "13.0.6", "features": ["kwargs-extension"]}
        required: true
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}
  PACKAGE_AND_VERSION: ${{ inputs.package_and_version }}
  GH_TOKEN: ${{ github.token }}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - name: Convert package and version to environment variables
        run: |
          cat <<EOF >> $GITHUB_ENV
          
          PACKAGE=$(echo "${PACKAGE_AND_VERSION}" | jq -r '.package')
          VERSION=$(echo "${PACKAGE_AND_VERSION}" | jq -r '.version')
          FEATURES=$(echo "${PACKAGE_AND_VERSION}" | jq -r '.features | join(" ")')

          INVENIO_VERSION=v$(echo "${PACKAGE_AND_VERSION}" | jq -r '.version')
          OAREPO_VERSION=oarepo-$(echo "${PACKAGE_AND_VERSION}" | jq -r '.version')

          EOF
          
          cat $GITHUB_ENV

      - name: Check if the package is already forked
        id: check_fork
        run: |
          mkdir -p .forks
          cd .forks
          gh repo clone oarepo/${PACKAGE}
          cd ${PACKAGE}
          git switch ${OAREPO_VERSION} && {
            echo "The fork already exists"
            echo "fork_already_exists=true" >> $GITHUB_ENV
            exit 0
          } || {
            echo "The fork does not exist, will try to create it"
            echo "fork_already_exists=false" >> $GITHUB_ENV
          }

      - name: Create a temporary fork of the package
        if: env.fork_already_exists != 'true'
        run: |
          cd .forks/${PACKAGE}
          git remote add upstream https://github.com/inveniosoftware/${PACKAGE}.git || true
          
          # remove a temporary fork
          git branch -D ${OAREPO_VERSION}-temporary || true
          
          # fetch invenio version and checkout it
          git fetch --tags upstream
          git fetch --all
          git checkout ${INVENIO_VERSION}
          
          # it is a tag, so create oarepo version from it
          git switch -c ${OAREPO_VERSION}-temporary

      - name: Apply feature branches
        if: env.fork_already_exists != 'true'
        run: |
          cd .forks/${PACKAGE}

          # Note to feature branches: feature branch must be forked from one of the vX.Y.Z tags,
          # not from the maintrunk. 
          
          get_vtag() {
            #
            # Get the vX.Y.Z tag that the feature branch is based on. We try all tags from the newest
            # to the oldest until we find the one that is in the feature branch ancestors
            #
            feature_branch="$1"
            vtags=$(git tag -l | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | sort -Vr)
            
            (
              # start from a well-known state
              git switch master || true
            
              # try to switch to the feature branch to check if it exists
              git switch $feature_branch || {
                echo "Feature branch ${feature_branch} does not exist!"
                exit 1
              }
            ) >&2

            for vtag in ${vtags}; do
              # check if the feature is based on vtag
              echo "Checking if ${feature_branch} is based on ${vtag}" >&2
              
              # we are on the feature branch, so we can use HEAD
              git merge-base --is-ancestor ${vtag} HEAD >/dev/null && {
                echo "Found vtag: $vtag" >&2
                echo "$vtag"      # return the vtag
                return 0
              } || true 
            done
          
            echo "Feature branch ${feature_branch} must be based on vX.Y.Z tag" >&2
            exit 1
          }
          
          apply_feature() {
            feature=$1
            feature_branch="oarepo-feature-${feature}"
            
            vtag=$(get_vtag ${feature_branch})

            git switch ${OAREPO_VERSION}-temporary
            git cherry-pick --allow-empty --allow-empty-message ${feature_branch} ^${vtag} 
          }
          
          for feature in ${FEATURES}; do
            apply_feature $feature
          done

      - name: Run tests on the patched package
        # always, just to make sure that nothing has broken in package deps
        run: |
          cd .forks/${PACKAGE}
          if [ $(git rev-parse --abbrev-ref HEAD) != ${OAREPO_VERSION}-temporary ] ; then
            echo "The current branch is not ${OAREPO_VERSION}-temporary - probably bug in previous steps"
            exit 1
          fi

          uv venv --python=${PYTHON_VERSION}
          source .venv/bin/activate
          uv pip install -e '.[tests,opensearch2,s3,devs]'
          if [ -x ./run-tests.sh ] ; then
            ./run-tests.sh
          elif [ -x ./run_tests.sh ] ; then
            ./run_tests.sh
          else
            pytest tests
          fi

      - name: Rename a temporary fork to the final fork
        if: env.fork_already_exists != 'true'
        run: |
          cd .forks/${PACKAGE}
          git switch ${OAREPO_VERSION}-temporary
          git branch -m ${OAREPO_VERSION}
          echo "push_required=True" >> $GITHUB_ENV

      - name: Check if the temporary fork is the same as if original, if not, remove the original and rename temp to original
        if: env.fork_already_exists == 'true'
        run: |
          cd .forks/${PACKAGE}
          git diff --exit-code ${OAREPO_VERSION} ${OAREPO_VERSION}-temporary || {
            git branch -D ${OAREPO_VERSION}
            git switch ${OAREPO_VERSION}-temporary
            git branch -m ${OAREPO_VERSION}
            echo "push_required=True" >> $GITHUB_ENV
          }
#
#      - name: Push the fork to the remote
#        if: env.push_required == 'true'
#        run: |
#          cd .forks/${PACKAGE}
#          git push origin ${OAREPO_VERSION} --force
