# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create OARepo package and put it into temporary artifacts

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string
    outputs:
      oarepo_tag:
        description: "OARepo tag"
        value: ${{ jobs.main.outputs.oarepo_tag }}

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - name: Checkout oarepo/oarepo under ./oarepo
        uses: actions/checkout@v4
        with:
          repository: "oarepo/oarepo"
          ref: "rdm-${{ env.OAREPO_VERSION }}"
          token: "${{ secrets.INTEGRATION_TEST }}"
          path: "oarepo"

      - name: Download artifacts from extract_requirements
        uses: actions/download-artifact@v4
        with:
          name: rdm_versions
          path: artifacts/requirements

      - name: Download artifacts from extract_requirements
        uses: actions/download-artifact@v4
        with:
          name: fork_versions
          path: artifacts/fork_versions

      - name: Create the pyproject.toml with dependencies (+forks)
        run: |
          cd oarepo
          bt_apply_versions_and_forks_to_pyproject \
              ${OAREPO_VERSION} \
              ../artifacts/requirements/rdm_requirements.json \
              ../artifacts/requirements/rdm_test_requirements.json \
              ../artifacts/fork_versions/forks_and_versions.json \
              pyproject.toml oarepo/version.py

      - name: Add react dependencies
        run: |
          cp artifacts/requirements/react-dependencies.json oarepo/oarepo/react-dependencies.json

      - name: Get the version tag and store it for later use
        run: |
          OAREPO_TAG=$(cat oarepo/version.py | grep __version__ | cut -d '"' -f 2)
          echo "oarepo_tag=${OAREPO_TAG}" | tee -a $GITHUB_OUTPUT

      - name: Store the whole package into artifacts
        uses: actions/upload-artifact@v4
        with:
          name: oarepo
          path: oarepo
