# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create a simple repository with the oarepo library

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - name: Start services
        uses: ./github/actions/start_services

      - name: Download artifacts from extract_requirements
        uses: actions/download-artifact@v4
        with:
          name: oarepo
          path: artifacts/oarepo

      - name: Install simple repository
        uses: ./.github/actions/install_simple_repo
        with:
          oarepo-version: ${{ inputs.oarepo }}
          python-version: ${{ inputs.python }}
          extras: "[tests]"

      - name: Run pytest tests
        run: |
          cd simple-repository
          pytest tests