# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Install and run UI tests in a simple repository

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - name: Start services
        uses: ./.github/actions/start_services

      - name: Download artifacts from extract_requirements
        uses: actions/download-artifact@v4
        with:
          name: oarepo
          path: artifacts/oarepo

      - name: Install simple repository
        uses: ./.github/actions/install_simple_repo
        with:
          oarepo-version: ${{ inputs.oarepo }}
          python-version: ${{ inputs.python }}

      - name: Install UI test dependencies
        run: |
          cd ui_tests/
          pwd
          npm ci
          npm install mocha -g

      - name: Run UI tests
        env:
          REST_URL: https://127.0.0.1:5000/api/simple-records
        run: |
          source .venv-tests/bin/activate
          export INVENIO_INSTANCE_PATH=$PWD/simple_repo/instance
          export SRVLOG=$PWD/invenio_run.log
          /bin/echo -e "\n=== invenio tokens create: ==="
          TOKEN=$(invenio tokens create -n test -u test@test.com)
          /bin/echo -e "status: $?\n$TOKEN"
          /bin/echo -e "\n=== invenio run: ==="
          invenio run --cert ./simple_repo/test.crt --key ./simple_repo/test.key > $SRVLOG 2>&1 &
          INVEPID=$!
          trap "kill $INVEPID &>/dev/null; /bin/echo -e '\n=== $SRVLOG: ==='; cat $SRVLOG" EXIT
          /bin/echo "  PID: $INVEPID"
          sleep 8

          cd ui_tests/test/
          pwd
          mocha invenioIntegrationTests.spec.js
