# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Commit and push oarepo

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string
      oarepo_tag:
        description: "OARepo tag"
        required: true
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}
  OAREPO_TAG: ${{ inputs.oarepo_tag }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Setup environment variables
        uses: ./.github/actions/setup_env
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - name: Download artifacts from create-oarepo-package
        uses: actions/download-artifact@v4
        with:
          name: oarepo
          path: oarepo-new

      - name: Checkout oarepo/oarepo under ./oarepo
        uses: actions/checkout@v4
        with:
          repository: "oarepo/oarepo"
          ref: "rdm-${{ env.OAREPO_VERSION }}"
          token: "${{ secrets.INTEGRATION_TEST }}"
          path: "oarepo"

      - name: Patch oarepo
        run: |
          cd oarepo
          cp ../oarepo-new/pyproject.toml .
          cp ../oarepo-new/oarepo/version.py .
          cp ../oarepo-new/oarepo/react-dependencies.json .

      - name: Commit and Push generated OARepo pyproject.toml with new requirements
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[invenio-integration-tests] update requirements inside pyproject.toml to make release ${{ env.OAREPO_TAG }}"
          branch: "rdm-${{ env.OAREPO_VERSION }}"
          file_pattern: pyproject.toml oarepo/version.py oarepo/react-dependencies.json
          repository: oarepo
          commit_user_name: integration-tests
          commit_user_email: integration-tests@oarepo.org
          tagging_message: ${{ env.OAREPO_TAG }}
          # Optional options appended to `git-push`
          push_options: '--force'
