# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create oarepo release

# This is the main script to be run to create a new release of oarepo tooling.
# It is triggered manually by the user or automatically during weekly builds.
#
# What it does
#   1. gets the appropriate version of invenio-app-rdm
#      extract dependencies and get the versions of the dependencies, serialize those to a json artefact
#   2. install the rdm and test that it can be compiled and run some basal tests
#   3. if there are any feature branches for invenio sources, apply those and run tests to make sure
#      that the feature branches are compatible with the current version of invenio. If everything is
#      ok, push the merged feature branches to the oarepo-<invenio-version> branch.
#   3. Install RDM with the branched forks and run tests to make sure that the branched forks are compatible
#      when used together.
#   4. create the final requirements file for the oarepo version, using the branched forks
#   5. create the pyproject.toml for the oarepo library
#   6. create a simple repository with the oarepo library, run REST, UI and pytest tests
#   7. create a new release of oarepo library and upload it to pypi

on:
  workflow_dispatch:
    inputs:
      oarepo:
        description: OARepo version (12, 13, ...)
        required: true
        default: 12
      python:
        description: Python version
        required: true
        default: "3.12"

permissions:
  id-token: write
  contents: write

jobs:
  extract_requirements:
    name: Extract requirements
    uses: ./.github/workflows/01-extract-requirements.yaml
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}

  test_rdm:
    name: Test RDM
    needs: extract_requirements
    uses: ./.github/workflows/03-install-rdm-and-test.yaml
    secrets: inherit
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}

  get_fork_versions:
    name: Get fork versions
    uses: ./.github/workflows/02-get-fork-versions.yaml
    needs:
      - extract_requirements
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}

  build_and_test_forks:
    name: ${{ matrix.package_and_version }} and test
    needs: get_fork_versions
    strategy:
      matrix:
        package_and_version: ${{ fromJSON(needs.get_fork_versions.outputs.forks_and_versions) }}
      fail-fast: false
    uses: ./.github/workflows/04-create-fork.yaml
    secrets: inherit
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}
      package_and_version: ${{ matrix.package_and_version }}

  create_oarepo_package:
    name: Create oarepo package
    needs:
    - build_and_test_forks
    uses: ./.github/workflows/05-create-oarepo-package.yaml
    secrets: inherit
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}

  test_simple_repository_pytest:
    name: PyTest simple repository
    needs:
    - create_oarepo_package
    - build_and_test_forks
    uses: ./.github/workflows/06-simple-repository-pytest.yaml
    secrets: inherit
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}

  test_simple_repository_rest:
    name: REST tests simple repository
    needs:
    - create_oarepo_package
    - build_and_test_forks
    uses: ./.github/workflows/07-simple-repository-rest.yaml
    secrets: inherit
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}

  test_simple_repository_ui:
    name: UI tests simple repository
    needs:
    - create_oarepo_package
    - build_and_test_forks
    uses: ./.github/workflows/08-simple-repository-ui.yaml
    secrets: inherit
    with:
      oarepo: ${{ github.event.inputs.oarepo }}
      python: ${{ github.event.inputs.python }}

# maybe: more thorough tests with model builder

  # upload_oarepo_package:
  #   if: needs.create_oarepo_package.outputs.version_changed == 'true'
  #   name: Upload oarepo
  #   needs:
  #   - test_simple_repository_pytest
  #   - test_simple_repository_rest
  #   - test_simple_repository_ui
  #   - test_rdm
  #   - create_oarepo_package
  #   uses: ./.github/workflows/09-commit-push-oarepo.yaml
  #   secrets: inherit
  #   with:
  #     oarepo: ${{ github.event.inputs.oarepo }}
  #     python: ${{ github.event.inputs.python }}
  #     oarepo_tag: ${{ needs.create_oarepo_package.outputs.oarepo_tag }}
