# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create oarepo release

# This is the main script to be run to create a new release of oarepo tooling.
# It is triggered manually by the user or automatically during weekly builds.
#
# What it does
# 1. It checks out the repository and prepares the tools virtualenv.
# 2. It determines the base repository to use for the testrig (oarepo/invenio-testrig for testing, zenodo/zenodo-rdm for production) and gets the list of patches to apply from the invenio-forks.yaml configuration file.
# 3. It runs the invenio-testrig workflow to test the patches on the base repository
on:
  workflow_dispatch:
    inputs:
      python:
        description: Python version
        required: true
        default: "3.14.2"
      dev-release:
        description: Whether to create a dev release (with .dev suffix)
        required: true
        type: boolean
        default: false

env:
  PYTHON_VERSION: ${{ github.event.inputs.python || '3.14.2' }}
  DEV_RELEASE: ${{ github.event.inputs.dev-release || false }}

permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      base_repository: ${{ steps.set-repository.outputs.base_repository }}
      patches: ${{ steps.set-repository.outputs.patches }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Prepare python and tools
        uses: ./.github/actions/action-install-tools
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set the correct repository for the testrig and get a list of patches to apply
        id: set-repository
        shell: bash
        run: |
          # repository is zenodo/zenodo-rdm for production build, 
          # oarepo/inveniordm-reference-repo for testing

          if [ "${{ env.DEV_RELEASE }}" = "true" ]; then
            echo "DEV_RELEASE is true, using repository oarepo/inveniordm-reference-repo for testing"
            echo "base_repository=oarepo/inveniordm-reference-repo" >> $GITHUB_OUTPUT
          else
            echo "DEV_RELEASE is false, using repository zenodo/zenodo-rdm for production build" 
            echo "base_repository=zenodo/zenodo-rdm" >> $GITHUB_OUTPUT
          fi

          invenio-integration-tests setup invenio-forks.yaml test.json
          mapfile -t patches < <(jq -r '.patches[]' test.json)

          echo "patches=${patches[*]}" >> $GITHUB_OUTPUT

  run_invenio_testrig:
    needs: prepare
    uses: oarepo/invenio-testrig/.github/workflows/verify-patches.yml@master
    with:
      name: Extract requirements from Zenodo and test the forks
      repository: ${{ needs.prepare.outputs.base_repository }}
      disable-codestyle-checks: true
      python-version: 3.14.2
      skip-report: true
      patches: ${{ needs.prepare.outputs.patches }}
      patch-mode: "pinned-rebase"
      test-mode: "stop-on-success" # do not run unpatched tests if the patches are ok
