# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Create oarepo release

# This is the main script to be run to create a new release of oarepo tooling.
# It is triggered manually by the user or automatically during weekly builds.
#
# What it does
# 1. It checks out the repository and prepares the tools virtualenv.
# 2. It determines the base repository to use for the testrig (oarepo/invenio-testrig for testing, zenodo/zenodo-rdm for production) and gets the list of patches to apply from the invenio-forks.yaml configuration file.
# 3. It runs the invenio-testrig workflow to test the patches on the base repository
on:
  workflow_dispatch:
    inputs:
      python:
        description: Python version
        required: true
        default: "3.14.2"

env:
  PYTHON_VERSION: ${{ github.event.inputs.python || '3.14.2' }}
  REFERENCE_REPO: "oarepo/inveniordm-reference-repo"
  IGNORED_DEPENDENCIES: latest-build,latest-build-instance,pywin32,coverage,pytest,pytest-cov,pytest-flask,pytest-github-actions-annotate-failures,pytest-invenio,pytest-isort,pytest-pycodestyle,pytest-pydocstyle,faker,selenium,docker,docker-services-cli,check-manifest,isort,pycodestyle,pydocstyle,ruff,types-beautifulsoup4,types-certifi,types-dateparser,types-html5lib,types-pyyaml,types-urllib3,types-webencodings,types-xmltodict,mypy-extensions,build,pyproject-hooks,setuptools,distlib,cookiecutter,invenio-cli,ipython,ipython-pygments-lexers,pdbpp,fancycompleter,pyreadline3,pyrepl,flask-debugtoolbar,flask-shell-ipython,pipenv,pipfile,virtualenv,jupyter-client,jupyter-core,jupyterlab-pygments,nbclient,nbconvert,nbformat,pywin32,watchdog
permissions:
  id-token: write
  contents: write
  pages: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      base_repository: ${{ steps.set-repository.outputs.base_repository }}
      patches: ${{ steps.set-repository.outputs.patches }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Prepare python and tools
        uses: ./.github/actions/action-install-tools
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set the correct repository for the testrig and get a list of patches to apply
        id: set-repository
        shell: bash
        run: |
          # Use oarepo/inveniordm-reference-repo for testing
          echo "Using repository ${REFERENCE_REPO} for the testrig"
          echo "base_repository=${REFERENCE_REPO}" >> $GITHUB_OUTPUT

          invenio-integration-tests setup invenio-forks.yaml workdir
          mapfile -t patches < <(jq -r '.patches[]' workdir/integration-tests-config.json)

          echo "patches=${patches[*]}" >> $GITHUB_OUTPUT

      - name: Store the integration-tests-config.json as an artifact for the next jobs
        uses: actions/upload-artifact@v6
        with:
          name: integration-tests-config
          path: workdir/integration-tests-config.json

  run_invenio_testrig:
    needs: prepare
    uses: oarepo/invenio-testrig/.github/workflows/verify-patches.yml@master
    with:
      name: Extract requirements from Zenodo and test the forks
      repository: ${{ needs.prepare.outputs.base_repository }}
      disable-codestyle-checks: true
      python-version: 3.14.2
      skip-report: true
      patches: ${{ needs.prepare.outputs.patches }}
      patch-mode: "pinned"
      test-mode: "stop-on-success" # do not run unpatched tests if the patches are ok
      skip-tests: false

  upload_patches_to_pypi:
    needs: run_invenio_testrig
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Prepare python and tools
        uses: ./.github/actions/action-install-tools
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Download the workdir artifact
        uses: actions/download-artifact@v7
        with:
          name: workdir

      - name: Untar the workdir artifact
        shell: bash
        run: |
          mkdir -p workdir
          tar -xzf workdir.tar.gz -C workdir --strip-components=1
          ls -la workdir

      - name: Download the integration-tests-config artifact and put it to the workdir
        uses: actions/download-artifact@v7
        with:
          name: integration-tests-config

      - name: Move the downloaded integration-tests-config artifact to the workdir
        shell: bash
        run: |
          ls -la
          mv integration-tests-config.json workdir/integration-tests-config.json

      - name: Upload original packages to the package registry
        shell: bash
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          invenio-integration-tests upload-original workdir

      - name: Update entrypoints in patched packages
        shell: bash
        run: |
          invenio-integration-tests update-entrypoints workdir

      - name: Find distributions for patched packages
        shell: bash
        run: |
          invenio-integration-tests find-distributions workdir

      - name: Build source and wheel distributions
        shell: bash
        run: |
          invenio-integration-tests build-distributions workdir

      - name: Upload distributions to CESNET registry
        shell: bash
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          invenio-integration-tests upload-distributions workdir

      - name: Create github app token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.OAREPO_BUMP_VERSION_CLIENT_ID }}
          private-key: ${{ secrets.OAREPO_BUMP_VERSION_CLIENT_PASSWORD }}
          owner: oarepo
          repositories: oarepo

      - name: Get OARepo version from the testrig configuration
        id: get-version
        shell: bash
        run: |
          OAREPO_VERSION=$(invenio-integration-tests oarepo-version --major workdir)
          RDM_VERSION=$(invenio-integration-tests oarepo-version workdir)
          echo "OAREPO_VERSION=$OAREPO_VERSION" >> $GITHUB_ENV
          echo "RDM_VERSION=$RDM_VERSION" >> $GITHUB_ENV
          echo "Going to create release for OARepo version $OAREPO_VERSION and $RDM_VERSION"

      - name: Checkout oarepo/oarepo under workdir/oarepo
        uses: actions/checkout@v6
        with:
          repository: "oarepo/oarepo"
          ref: "rdm-${{ env.OAREPO_VERSION }}"
          token: ${{ steps.app-token.outputs.token }}
          path: "workdir/oarepo"
          persist-credentials: true

      - name: Update oarepo package version and dependencies
        shell: bash
        run: |
          invenio-integration-tests update-oarepo workdir --ignored-dependencies "${IGNORED_DEPENDENCIES}"
          echo "OAREPO_TAG=$(cat workdir/oarepo_version.txt)" >> $GITHUB_ENV

      - name: Commit and Push generated OARepo pyproject.toml with new requirements
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[invenio-integration-tests] update requirements inside pyproject.toml to make release ${{ env.OAREPO_TAG }}"
          branch: "rdm-${{ env.OAREPO_VERSION }}"
          file_pattern: pyproject.toml oarepo/version.py oarepo/react-dependencies.json
          repository: workdir/oarepo
          commit_user_name: integration-tests
          commit_user_email: integration-tests@oarepo.org
          tagging_message: ${{ env.OAREPO_TAG }}
          # Optional options appended to `git-push`
          push_options: "--force"
