# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Extract requirements from Invenio RDM

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}

jobs:
  extract_requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment variables
        uses: ./.github/actions/setup_env      # TODO: change the branch when merging to main
        with:
          python-version: ${{ inputs.python }}
          oarepo-version: ${{ inputs.oarepo }}

      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Install python
        uses: ./.github/actions/install_python      # TODO: change the branch when merging to main
        with:
          python-version: ${{ inputs.python }}

      - name: Create artifacts directory
        run: |
          mkdir -p artifacts

      - name: Lock app-rdm version
        run: |
          uv init rdm --python $PYTHON_VERSION
          cd rdm
          uv add "$APP_RDM_PRODUCTION_VERSION"
          cat pyproject.toml
          uv pip freeze | sort -u >../artifacts/rdm_requirements.txt
          uv pip list --format=json >../artifacts/rdm_requirements.json
          cp uv.lock ../artifacts/rdm.uv.lock

      - name: Lock app-rdm + tests version
        run: |
          uv init rdm_tests --python $PYTHON_VERSION
          cd rdm_tests
          uv add "$APP_RDM_TEST_VERSION"
          cat pyproject.toml
          uv pip freeze | sort -u >../artifacts/rdm_test_requirements.txt
          uv pip list --format=json >../artifacts/rdm_test_requirements.json
          cp uv.lock ../artifacts/rdm_test.uv.lock

      - name: Check that the two requirements are compatible
        # , that is, that the test requirements are a superset of the requirements
        run: |
          echo "Diff between the requirements and test requirements"
          diff -u artifacts/rdm_requirements.txt artifacts/rdm_test_requirements.txt | egrep -v '^(---|[+][+][+])' | egrep "^(-|[+])" | tee test_changes.diff || true
          cat test_changes.diff | grep '^-' | while read ; do
            pkg=$(echo $REPLY | sed 's/^-\([^=]*\)==.*$/\1/')
            versions="$(cat test_changes.diff  | grep $pkg | tr '\n' ' ')"
            echo "::warning::RDM requirements and RDM test requirements are not compatible in package: $versions"
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rdm_versions
          path: artifacts
          if-no-files-found: error

      - name: Display Requirements
        run: |
          echo "========= RDM Requirements ========="
          cat artifacts/rdm_requirements.txt
          echo
          echo
          echo "========= RDM Test Requirements ========="
          cat artifacts/rdm_test_requirements.txt