# -*- coding: utf-8 -*-
#
# Copyright (C) 2024 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Get oarepo forks and their new versions

on:
  workflow_call:
    inputs:
      oarepo:
        description: OARepo version (12, ...)
        required: true
        default: "12"
        type: string
      python:
        description: Python version
        required: true
        default: "3.12"
        type: string

    outputs:
      forks_and_versions:
        description: "Invenio forks and their versions"
        value: ${{ jobs.get_fork_versions.outputs.forks_and_versions }}

env:
  # keep the following consistent
  OAREPO_VERSION: ${{ inputs.oarepo }}
  PYTHON_VERSION: ${{ inputs.python }}

jobs:
  get_fork_versions:
    runs-on: ubuntu-latest
    outputs:
      forks_and_versions: ${{ steps.get_fork_versions.outputs.forks_and_versions }}

    steps:
      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Download artifacts from extract_requirements
        uses: actions/download-artifact@v4
        with:
          name: artifacts/requirements
          path: artifacts/requirements

      - name: Install python and tools
        uses: ./.github/actions/install_python
        with:
          python-version: ${{ inputs.python }}

      - id: get_fork_versions
        name: Get forks and their versions
        run: |
            exit 1