# -*- coding: utf-8 -*-
#
# Copyright (C) 2023 CESNET.
#
# invenio-integration-tests is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: Oarepo integr.test builder

on:
  workflow_dispatch:

env:
  # keep the following consistent
  OAREPO_VERSION: 12
  APP_RDM_PRODUCTION_VERSION: "invenio-app-rdm[opensearch2,s3]>=12.0.0b2.dev1,<13"
  APP_RDM_TEST_VERSION: "invenio-app-rdm[opensearch2,s3,tests]>=12.0.0b2.dev1,<13"
  PYTHON_VERSION: "3.10"
  PYTHON: "python3.10"

  OPENSEARCH_PORT: 9200
  OPENSEARCH_VERSION: 2
  REDIS_VERSION: 6
  POSTGRES_VERSION: 14
  POSTGRES_DB: invenio


jobs:
  start_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - db: postgres
            invenio-sqlalchemy-database-uri: "postgresql+psycopg2://localhost:5432/invenio"
          - db: sqlite
            invenio-sqlalchemy-database-uri: "sqlite:////tmp/test.db"

    env:
      INVENIO_SQLALCHEMY_DATABASE_URI: ${{ matrix.invenio-sqlalchemy-database-uri }}

    outputs:
      newtag: ${{ steps.bump_version.outputs.newtag }}

    steps:
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Opensearch ${{ env.OPENSEARCH_VERSION }}
        uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: ${{ env.OPENSEARCH_VERSION }}
      - name: Redis ${{ env.REDIS_VERSION }}
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ env.REDIS_VERSION }}
      - name: Postgres ${{ env.POSTGRES_VERSION }}
        uses: ankane/setup-postgres@v1
        with:
          postgres-version: ${{ env.POSTGRES_VERSION }}
          database: ${{ env.POSTGRES_DB }}
        if: matrix.db == 'postgres'

      - name: Test opensearch on port ${{ env.OPENSEARCH_PORT }}
        run: |
          netstat -ntlp
          curl -s http://localhost:${{ env.OPENSEARCH_PORT }}
      - name: "Test redis: redis-cli ping"
        run: |
          redis-cli ping
      - name: Test postgres version ${{ env.POSTGRES_VERSION }}
        run: |
          psql -d ${{ env.POSTGRES_DB }} -c 'SHOW server_version'
        if: matrix.db == 'postgres'

      - name: Set up Node20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout oarepo/invenio-integration-tests
        uses: actions/checkout@v4

      - name: Show versions of programs
        run: |
          node --version
          $PYTHON --version

      - name: Create test virtualenv
        run: |
          $PYTHON -m venv .venv-tests
          source .venv-tests/bin/activate
          pip install -U setuptools pip wheel
          pip list

      - name: Create main repository venv
        run: |

          python3 -m venv .venv-repository
          source .venv-repository/bin/activate
          pip install -U setuptools pip wheel

      - name: Install tools to project/.venv-tools
        run: |
          
          python3 -m venv .venv-tools
          source .venv-tools/bin/activate
          pip install -U setuptools pip wheel
          
          # install version bump
          pip install bump
          
          # install tools for merging requirements
          pip install click toml requirements-parser semver

          # install uv
          pip install uv

          UV=$(which uv)
          deactivate
          $UV --version
          echo "UV=$UV" >> "$GITHUB_ENV"

      - name: Resolve invenio-app-rdm dependencies
        run: |
          echo "$APP_RDM_PRODUCTION_VERSION" >requirements.in
          
          .venv-tools/bin/uv pip compile requirements.in >requirements-production.txt.comments
          cat requirements-production.txt.comments | sort | egrep -v '^\s*#' >requirements-production.txt

      - name: Resolve invenio-app-rdm test dependencies
        run: |
          echo "$APP_RDM_TEST_VERSION" >requirements.in
          
          .venv-tools/bin/uv pip compile requirements.in >requirements-test.txt.comments
          cat requirements-test.txt.comments | sort | egrep -v '^\s*#' >requirements-test.txt


      - name: Checkout oarepo/oarepo under ./oarepo
        uses: actions/checkout@v4
        with:
          repository: "oarepo/oarepo"
          ref: "rdm-${{ env.OAREPO_VERSION }}"
          token: "${{ secrets.INTEGRATION_TEST }}"
          path: "oarepo"

      - name: Generate requirements.txt file from the oarepo
        run: |
          set +e
          echo "./oarepo[rdm]" >requirements.in
          
          .venv-tools/bin/uv pip compile requirements.in  | grep -v "oarepo=" >requirements-oarepo.txt.comments 

          cat requirements-oarepo.txt.comments | sort | egrep -v '^\s*#' >requirements-oarepo.txt
          set -e

      - name: Generate test requirements.txt file from the oarepo
        run: |
          set +e
          
          echo "./oarepo[rdm,tests]" >requirements.in
          
          .venv-tools/bin/uv pip compile requirements.in | grep -v "oarepo=" >requirements-oarepo-tests.txt.comments 

          cat requirements-oarepo-tests.txt.comments | sort | egrep -v '^\s*#' >requirements-oarepo-tests.txt
          set -e

      - name: Show the generated requirements files
        run: |
          echo "=============================="
          echo "New production requirements:"
          echo
          cat requirements-production.txt
          echo
          echo "=============================="
          echo "New test requirements:"
          echo
          cat requirements-test.txt
          echo
          echo "=============================="
          echo "Previous oarepo production requirements:"
          echo
          cat requirements-oarepo.txt
          echo
          echo "=============================="
          echo "Previous oarepo test requirements:"
          echo
          cat requirements-oarepo-tests.txt

      - name: Show a diff for production and test requirements
        run: |
          echo "=============================="
          echo "Diff production requirements:"
          echo
          diff -buN requirements-oarepo.txt requirements-production.txt || true
          echo
          echo "=============================="
          echo "Diff test requirements:"
          echo
          diff -buN requirements-oarepo-tests.txt requirements-test.txt || true

      - name: Compare if the requirements have changed and skip the rest of steps if not
        run: |
          if [[ $(diff requirements-production.txt requirements-oarepo.txt) ]]; then
            echo "Production requirements have changed, will continue with tests"
            RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION=yes
          elif [[ $(diff requirements-test.txt requirements-oarepo-tests.txt) ]]; then
            echo "Test requirements have changed, will continue with tests"
            RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION=yes
          else
            echo "Requirements have not changed, will skip the rest of the processing"
            RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION=no
          fi

          echo "RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION=$RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION" >> "$GITHUB_ENV"

      - name: Generate a new oarepo/pyproject.toml file
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          source .venv-tools/bin/activate
          echo "Old pyproject.toml"
          cat oarepo/pyproject.toml
          $PYTHON scripts/merge_requirements_to_pyproject_toml.py requirements-production.txt requirements-test.txt oarepo/pyproject.toml


      - name: Create react dependencies extraction venv
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          python3 -m venv .venv-react
          source .venv-react/bin/activate
          pip install -U setuptools pip wheel

      - name: Install rdm to the extraction virtualenv
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          source .venv-react/bin/activate
          .venv-tools/bin/uv pip install -r requirements-production.txt

      - name: Run the extraction script
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          source .venv-react/bin/activate
          python scripts/get_react_dependencies.py >oarepo/oarepo/react-dependencies.json

      - name: Bump oarepo version
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        id: bump_version
        run: |
          cd oarepo

          /bin/echo -e "\n=== original oarepo version: ==="
          grep '__version__' oarepo/version.py

          /bin/echo -e "\n=== BUMP: ==="
          NEWTAG=$(${GITHUB_WORKSPACE}/.venv-tools/bin/bump oarepo/version.py oarepo/version.py)
          NEWTAG1=$(${GITHUB_WORKSPACE}/.venv-tools/bin/bump pyproject.toml pyproject.toml)

          echo "new version: $NEWTAG, inside pyproject $NEWTAG1"
          if [[ "$NEWTAG" != "$NEWTAG1" ]]; then
            echo "ERROR: versions in oarepo/version.py and pyproject.toml differ"
            exit 1
          fi
          echo "NEWTAG=$NEWTAG" >> "$GITHUB_ENV"
          echo "newtag=$NEWTAG" >> "$GITHUB_OUTPUT"


      - name: Install simple repo
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          source .venv-tests/bin/activate

          # install in non-editable mode
          .venv-tools/bin/uv pip install ./oarepo

          cd simple_repo
          ../.venv-tools/bin/uv pip install -e . --no-deps

      - name: Prepare invenio inside simple repo
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          source .venv-tests/bin/activate
          export INVENIO_INSTANCE_PATH=$PWD/simple_repo/instance
          /bin/echo -e "\nINVENIO_INSTANCE_PATH: $INVENIO_INSTANCE_PATH"
          /bin/echo -e "\nINVENIO_SQLALCHEMY_DATABASE_URI: $INVENIO_SQLALCHEMY_DATABASE_URI"
          /bin/echo -e "\n=== invenio db init: ==="
          invenio db init
          /bin/echo -e "\n=== invenio db create: ==="
          invenio db create
          /bin/echo -e "\n=== invenio index init: ==="
          invenio index init
          /bin/echo -e "\n=== invenio webpack buildall: ==="
          invenio webpack buildall
          /bin/echo -e "\n=== invenio users create: ==="
          invenio users create --password aaaaaa -a -c test@test.com

      - name: test REST and pytest
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        env:
          REST_URL: https://127.0.0.1:5000/api/simple-records
        run: |
          source .venv-tests/bin/activate
          export INVENIO_INSTANCE_PATH=$PWD/simple_repo/instance
          export SRVLOG=$PWD/invenio_run.log
          /bin/echo -e "\n=== invenio tokens create: ==="
          TOKEN=$(invenio tokens create -n test -u test@test.com)
          /bin/echo -e "status: $?\n$TOKEN"
          /bin/echo -e "\n=== invenio run: ==="
          invenio run --cert ./simple_repo/test.crt --key ./simple_repo/test.key > $SRVLOG 2>&1 &
          INVEPID=$!
          trap "kill $INVEPID &>/dev/null; /bin/echo -e '\n=== $SRVLOG: ==='; cat $SRVLOG" EXIT
          /bin/echo "  PID: $INVEPID"
          sleep 8

          /bin/echo -e "\n=== REST 1 (POST new record w/o token): ==="
          RESULT=$(curl -sk -d '{"title":"blah"}' -X POST -H "content-type: application/json" "$REST_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -eq 403 ]]

          /bin/echo -e "\n=== REST 2 (POST new record): ==="
          RESULT=$(curl -sk -H "Authorization: Bearer $TOKEN" -d '{"title":"blah"}' -X POST -H "content-type: application/json" "$REST_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -lt 400 ]]
          RECORD_URL=$(jq -r '.links.self' <<<"$RESULT")
          /bin/echo -e "status: $?\nRECORD_URL: $RECORD_URL"

          /bin/echo -e "\n=== REST 3 (GET record): ==="
          RESULT=$(curl -sk "$RECORD_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -lt 400 ]]

          /bin/echo -e "\n=== REST 4 (PUT new title w/o token): ==="
          RESULT=$(curl -sk -d '{"title":"blah 1"}' -X PUT -H "content-type: application/json" "$RECORD_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -eq 403 ]]

          /bin/echo -e "\n=== REST 5 (PUT new title): ==="
          RESULT=$(curl -sk -H "Authorization: Bearer $TOKEN" -d '{"title":"blah 1"}' -X PUT -H "content-type: application/json" "$RECORD_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -lt 400 ]]

          /bin/echo -e "\n=== REST 6 (GET records on /api/simple-records): ==="
          RESULT=$(curl -sk -X GET "$REST_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -lt 400 ]]

          /bin/echo -e "\n=== REST 7 (DELETE record w/o token): ==="
          RESULT=$(curl -sk -X DELETE "$RECORD_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -eq 403 ]]

          /bin/echo -e "\n=== REST 8 (DELETE record): ==="
          RESULT=$(curl -sk -H "Authorization: Bearer $TOKEN" -X DELETE "$RECORD_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -lt 400 ]]

          /bin/echo -e "\n=== REST 9 (GET record): ==="
          RESULT=$(curl -sk "$RECORD_URL")
          /bin/echo -e "status: $?\n$RESULT"
          [[ $(jq '.status' <<<"$RESULT") -lt 500 ]]

      - name: Install UI test dependencies
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          cd ui_tests/
          pwd
          npm ci
          npm install mocha -g

      - name: Run UI tests
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        env:
          REST_URL: https://127.0.0.1:5000/api/simple-records
        run: |
          source .venv-tests/bin/activate
          export INVENIO_INSTANCE_PATH=$PWD/simple_repo/instance
          export SRVLOG=$PWD/invenio_run.log
          /bin/echo -e "\n=== invenio tokens create: ==="
          TOKEN=$(invenio tokens create -n test -u test@test.com)
          /bin/echo -e "status: $?\n$TOKEN"
          /bin/echo -e "\n=== invenio run: ==="
          invenio run --cert ./simple_repo/test.crt --key ./simple_repo/test.key > $SRVLOG 2>&1 &
          INVEPID=$!
          trap "kill $INVEPID &>/dev/null; /bin/echo -e '\n=== $SRVLOG: ==='; cat $SRVLOG" EXIT
          /bin/echo "  PID: $INVEPID"
          sleep 8

          cd ui_tests/test/
          pwd
          mocha invenioIntegrationTests.spec.js

          /bin/echo -e "\n=== invenio index destroy --yes-i-know: ==="
          invenio index destroy --yes-i-know
          /bin/echo -e "\n=== invenio db destroy --yes-i-know: ==="
          invenio db destroy --yes-i-know


      - name: Install simple repo with python tests
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          source .venv-tests/bin/activate
          .venv-tools/bin/uv pip install -e 'oarepo[tests]'
          cd simple_repo
          ../.venv-tools/bin/uv pip install -e '.[tests]'


      - name: Run pytest
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        run: |
          source .venv-tests/bin/activate
          export INVENIO_INSTANCE_PATH=$PWD/simple_repo/instance
          cd simple_repo
          /bin/echo -e "\n=== pytest tests: ==="
          pytest tests

      - name: Upload artifacts
        if: env.RUN_TESTS_AND_PUBLISH_NEW_OAREPO_VERSION == 'yes'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.db }}-artifacts4oarepo
          path: |
            oarepo/pyproject.toml
            oarepo/oarepo/version.py
            oarepo/oarepo/react-dependencies.json
          retention-days: 1


  push_to_oarepo:
    runs-on: ubuntu-latest
    needs: start_and_test
    env:
      # the newtag is empty if requirements have not changed, otherwise it is set to the new oarepo version
      NEWTAG: ${{ needs.start_and_test.outputs.newtag }}
    steps:
      - name: Intro debug
        run: |
          echo "About to push to oarepo, newtag: ${{ env.NEWTAG }}"
          echo "output from start_and_test job: ${{ needs.start_and_test.outputs.newtag }}"

      - name: Checkout oarepo/oarepo under ./oarepo
        if: env.NEWTAG != ''
        uses: actions/checkout@v4
        with:
          repository: "oarepo/oarepo"
          ref: "rdm-${{ env.OAREPO_VERSION }}"
          token: "${{ secrets.INTEGRATION_TEST }}"
          path: "oarepo"

      - name: Download artifacts
        if: env.NEWTAG != ''
        uses: actions/download-artifact@v4
        with:
          name: postgres-artifacts4oarepo
          path: oarepo

      - name: debug
        if: env.NEWTAG != ''
        run: |
          ls -l oarepo
          ls -l oarepo/oarepo
          echo -n "version:"
          cat oarepo/oarepo/version.py
          echo -n "pyproject.toml:"
          cat oarepo/pyproject.toml
          echo -n "react dependencies:"
          cat oarepo/oarepo/react-dependencies.json
          echo "newtag: ${{ env.NEWTAG }}"
          echo "event_name: ${{ github.event_name }}"

      - name: Commit and Push generated OARepo pyproject.toml with new requirements
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[invenio-integration-tests] update requirements inside pyproject.toml (tag ${{ env.NEWTAG }})"
          branch: "rdm-${{ env.OAREPO_VERSION }}"
          file_pattern: pyproject.toml oarepo/version.py oarepo/react-dependencies.json
          repository: oarepo
          commit_user_name: integration-tests
          commit_user_email: integration-tests@oarepo.org
          tagging_message: ${{ env.NEWTAG }}
          # Optional options appended to `git-push`
          push_options: '--force'
        if: success() && (env.NEWTAG != '') && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
